export const projects = [
    {
        title: "Project Drew",
        shipImage: "./ships/wing-starfighter.png",
        planetImage: "./planets/mars-planet.png",
        description: "A personal site for a lawyer.",
        phase: "P3",
        skills: "React, TypeScript, Tailwind, Git, Figma",
        screens: "Desktop, Tablet, Mobile",
        link: "#",
    },
    {
        title: "KyLib",
        shipImage: "./ships/empire-ship.png",
        planetImage: "./planets/mercury-planet.png",
        description: "Your non-ordinary book libray.",
        phase: "P2",
        skills: "React, TypeScript, Tailwind, Node.js, MongoDB, Git, Figma",
        screens: "Desktop, Tablet, Mobile",
        link: "#",
    },
    {
        title: "InstaMe",
        shipImage: "./ships/rebellion-ship.png",
        planetImage: "./planets/uranus-planet.png",
        description: "Instagram dashboard.",
        phase: "P1",
        skills: "React, TypeScript, Tailwind, Node.js, MongoDB, Postman, Git, Figma",
        screens: "Desktop",
        link: "#",
    },
    {
        title: "Interactive Forest",
        shipImage: "./ships/lambda-class-shuttle-1.png",
        planetImage: "./planets/venus-planet.png",
        description: "An interactive experience through a forest",
        phase: "P4",
        skills: "TypeScript, Tailwind, Git, Figma",
        screens: "Desktop, Tablet, Mobile",
        link: "#",
    },
];